# Model Configuration
models:
  slm:
    phi-2:
      name: "microsoft/phi-2"
      max_length: 2048
      load_in_8bit: true
      device_map: "auto"
    
    llama-7b:
      name: "meta-llama/Llama-2-7b-hf"
      max_length: 4096
      load_in_8bit: true
      device_map: "auto"
    
    mistral-7b:
      name: "mistralai/Mistral-7B-v0.1"
      max_length: 8192
      load_in_8bit: true
      device_map: "auto"
  
  generalist:
    gpt-4:
      model: "gpt-4-turbo-preview"
      temperature: 0.1
      max_tokens: 1024
    
    gemini:
      model: "gemini-pro"
      temperature: 0.1
      max_output_tokens: 1024
    
    claude:
      model: "claude-3-opus-20240229"
      temperature: 0.1
      max_tokens: 1024

# LoRA Configuration
lora:
  r: 16
  lora_alpha: 32
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"

# DoRA Configuration
dora:
  r: 16
  lora_alpha: 32
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
  lora_dropout: 0.05
  use_dora: true
  bias: "none"
  task_type: "CAUSAL_LM"

# GRPO Configuration
grpo:
  learning_rate: 1e-5
  batch_size: 4
  mini_batch_size: 1
  gradient_accumulation_steps: 4
  ppo_epochs: 4
  max_grad_norm: 1.0
  vf_coef: 0.1
  cliprange: 0.2
  cliprange_value: 0.2
  gamma: 1.0
  lam: 0.95
  kl_penalty: "kl"
  target_kl: 0.1

# Generation Configuration
generation:
  max_new_tokens: 512
  temperature: 0.1
  top_p: 0.95
  top_k: 50
  repetition_penalty: 1.1
  do_sample: false
